// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvxhhnqkhepqaincukch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eGhobnFraGVwcWFpbmN1a2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NTAxMTAsImV4cCI6MjA3ODQyNjExMH0.kj6q6FKx4lGIggqTp8DVBBRO-tcq8pAjE454Px4RIog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});